# Generated by Django 3.0.7 on 2021-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_gst_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rate_with_gst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
