# Generated by Django 3.0.7 on 2021-09-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0012_auto_20210921_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product_name'),
        ),
    ]
